name: pull

on:
  pull_request:
    branches-ignore:
      - nightly
  push:
    branches:
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:
  schedule:
    - cron: 29 8 * * *  # about 1:29am PDT

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  linux-focal-py3_8-clang10-build:
    name: linux-focal-py3.8-clang10
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: linux-focal-py3.8-clang10
      docker-image-name: pytorch-linux-focal-py3.8-clang10
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "default", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
          { config: "crossref", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "crossref", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 1, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 2, num_shards: 3, runner: "linux.2xlarge" },
          { config: "dynamo", shard: 3, num_shards: 3, runner: "linux.2xlarge" },
        ]}

  linux-focal-py3_8-clang10-test:
    name: linux-focal-py3.8-clang10
    uses: ./.github/workflows/_linux-test.yml
    needs: linux-focal-py3_8-clang10-build
    with:
      build-environment: linux-focal-py3.8-clang10
      docker-image: ${{ needs.linux-focal-py3_8-clang10-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-focal-py3_8-clang10-build.outputs.test-matrix }}
